site_name: MISO LIMS
site_url: http://miso-lims.github.io
site_description: MISO LIMS
site_author: Genome Sequence Informatics, Ontario Institute for Cancer Research
site_favicon: images/favicon.ico
repo_url: https://github.com/miso-lims/miso-lims.github.io
copyright: Copyright &copy; 2019 <a href="https://oicr-gsi.github.io/">Genome Sequence Informatics</a>, <a href="http://oicr.on.ca">Ontario Institute for Cancer Research</a>

theme: readthedocs

nav:
  - About: index.md
  - MISO LIMS:
    - Getting Started: /projects/docs/
    - Walkthroughs: /projects/walkthroughs
    - User Manual: /projects/docs
  - Associated Software:
    - Run Scanner: /projects/runscanner